import { GallerySchema } from '@/schema/GallerySchema';

const mock_gallery: GallerySchema[] = [
    {
        id: 1,
        attributes: {
            name: 'galeria-principal',
            createdAt: '2024-07-30T12:17:52.557Z',
            updatedAt: '2024-07-30T12:17:54.048Z',
            publishedAt: '2024-07-30T12:17:54.042Z',
            images: {
                data: [
                    {
                        id: 4,
                        attributes: {
                            name: '4.jpg',
                            alternativeText: null,
                            caption: null,
                            width: 482,
                            height: 643,
                            formats: {
                                small: {
                                    ext: '.jpg',
                                    url: '/uploads/small_4_f60264e77f.jpg',
                                    hash: 'small_4_f60264e77f',
                                    mime: 'image/jpeg',
                                    name: 'small_4.jpg',
                                    path: null,
                                    size: 39.46,
                                    width: 375,
                                    height: 500,
                                    sizeInBytes: 39464,
                                },
                                thumbnail: {
                                    ext: '.jpg',
                                    url: '/uploads/thumbnail_4_f60264e77f.jpg',
                                    hash: 'thumbnail_4_f60264e77f',
                                    mime: 'image/jpeg',
                                    name: 'thumbnail_4.jpg',
                                    path: null,
                                    size: 5.06,
                                    width: 117,
                                    height: 156,
                                    sizeInBytes: 5062,
                                },
                            },
                            hash: '4_f60264e77f',
                            ext: '.jpg',
                            mime: 'image/jpeg',
                            size: 59.09,
                            url: '/uploads/4_f60264e77f.jpg',
                            previewUrl: null,
                            provider: 'local',
                            provider_metadata: null,
                            createdAt: '2024-07-28T17:01:52.973Z',
                            updatedAt: '2024-07-28T17:01:52.973Z',
                        },
                    },
                    {
                        id: 1,
                        attributes: {
                            name: '2.jpg',
                            alternativeText: null,
                            caption: null,
                            width: 482,
                            height: 322,
                            formats: {
                                thumbnail: {
                                    ext: '.jpg',
                                    url: '/uploads/thumbnail_2_6c27261a20.jpg',
                                    hash: 'thumbnail_2_6c27261a20',
                                    mime: 'image/jpeg',
                                    name: 'thumbnail_2.jpg',
                                    path: null,
                                    size: 8.52,
                                    width: 234,
                                    height: 156,
                                    sizeInBytes: 8522,
                                },
                            },
                            hash: '2_6c27261a20',
                            ext: '.jpg',
                            mime: 'image/jpeg',
                            size: 24.91,
                            url: '/uploads/2_6c27261a20.jpg',
                            previewUrl: null,
                            provider: 'local',
                            provider_metadata: null,
                            createdAt: '2024-07-28T17:01:52.940Z',
                            updatedAt: '2024-07-28T17:01:52.940Z',
                        },
                    },
                    {
                        id: 3,
                        attributes: {
                            name: '1.jpg',
                            alternativeText: null,
                            caption: null,
                            width: 455,
                            height: 683,
                            formats: {
                                small: {
                                    ext: '.jpg',
                                    url: '/uploads/small_1_ede856714a.jpg',
                                    hash: 'small_1_ede856714a',
                                    mime: 'image/jpeg',
                                    name: 'small_1.jpg',
                                    path: null,
                                    size: 33.03,
                                    width: 333,
                                    height: 500,
                                    sizeInBytes: 33030,
                                },
                                thumbnail: {
                                    ext: '.jpg',
                                    url: '/uploads/thumbnail_1_ede856714a.jpg',
                                    hash: 'thumbnail_1_ede856714a',
                                    mime: 'image/jpeg',
                                    name: 'thumbnail_1.jpg',
                                    path: null,
                                    size: 4.38,
                                    width: 104,
                                    height: 156,
                                    sizeInBytes: 4375,
                                },
                            },
                            hash: '1_ede856714a',
                            ext: '.jpg',
                            mime: 'image/jpeg',
                            size: 53.17,
                            url: '/uploads/1_ede856714a.jpg',
                            previewUrl: null,
                            provider: 'local',
                            provider_metadata: null,
                            createdAt: '2024-07-28T17:01:52.962Z',
                            updatedAt: '2024-07-28T17:01:52.962Z',
                        },
                    },
                    {
                        id: 2,
                        attributes: {
                            name: '3.jpg',
                            alternativeText: null,
                            caption: null,
                            width: 482,
                            height: 321,
                            formats: {
                                thumbnail: {
                                    ext: '.jpg',
                                    url: '/uploads/thumbnail_3_cb7900a1e8.jpg',
                                    hash: 'thumbnail_3_cb7900a1e8',
                                    mime: 'image/jpeg',
                                    name: 'thumbnail_3.jpg',
                                    path: null,
                                    size: 8.21,
                                    width: 234,
                                    height: 156,
                                    sizeInBytes: 8209,
                                },
                            },
                            hash: '3_cb7900a1e8',
                            ext: '.jpg',
                            mime: 'image/jpeg',
                            size: 23.33,
                            url: '/uploads/3_cb7900a1e8.jpg',
                            previewUrl: null,
                            provider: 'local',
                            provider_metadata: null,
                            createdAt: '2024-07-28T17:01:52.957Z',
                            updatedAt: '2024-07-28T17:01:52.957Z',
                        },
                    },
                ],
            },
        },
    },
];

export default mock_gallery;
